# Generated by Django 4.2.18 on 2025-02-04 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tierra_media.backpack'),
        ),
        migrations.AlterField(
            model_name='backpack',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tierra_media.character'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tierra_media.backpack'),
        ),
    ]
