# Generated by Django 4.2.18 on 2025-02-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0002_alter_armor_equipment_alter_backpack_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierra_media.backpack'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierra_media.backpack'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
