# Generated by Django 4.2.18 on 2025-02-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0003_alter_armor_equipment_alter_armor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='character',
        ),
        migrations.AddField(
            model_name='relationship',
            name='character',
            field=models.ManyToManyField(to='tierra_media.character'),
        ),
    ]
