# Generated by Django 4.2.18 on 2025-02-04 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0004_remove_relationship_character_relationship_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='character2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='relation_with', to='tierra_media.character'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='character',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='type',
            field=models.CharField(max_length=51),
        ),
        migrations.AddField(
            model_name='relationship',
            name='character',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='character', to='tierra_media.character'),
            preserve_default=False,
        ),
    ]
