# Generated by Django 4.2.18 on 2025-02-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0005_relationship_character2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='character',
            new_name='character_1',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='character2',
            new_name='character_2',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
