# Generated by Django 5.1.5 on 2025-02-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0006_rename_character_relationship_character_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='defense',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='health',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='character',
            name='max_health',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
