# Generated by Django 4.2.18 on 2025-02-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0007_alter_character_defense_alter_character_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
