# Generated by Django 4.2.19 on 2025-02-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0009_alter_character_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='equipment',
        ),
        migrations.AddField(
            model_name='armor',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tierra_media.character'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tierra_media.character'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Backpack',
        ),
    ]
