# Generated by Django 4.2.19 on 2025-02-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0010_remove_armor_equipment_remove_weapon_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='owner',
        ),
        migrations.AddField(
            model_name='armor',
            name='owner',
            field=models.ManyToManyField(to='tierra_media.character'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='owner',
            field=models.ManyToManyField(to='tierra_media.character'),
        ),
    ]
