# Generated by Django 4.2.19 on 2025-02-10 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0011_remove_armor_owner_remove_weapon_owner_armor_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='npc_owned',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_health', models.IntegerField(default=250)),
                ('health', models.IntegerField(default=250)),
                ('defense', models.IntegerField(default=50)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tierra_media.character')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tierra_media.faction')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tierra_media.location')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tierra_media.race')),
            ],
        ),
    ]
