# Generated by Django 4.2.18 on 2025-02-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0012_weapon_npc_owned_npc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonArmor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('defense', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommonWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('damage', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniqueArmor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('defense', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniqueWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('damage', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='npc',
            name='character',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='faction',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='location',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='race',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='owner',
        ),
        migrations.AddField(
            model_name='character',
            name='npc',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Armor',
        ),
        migrations.DeleteModel(
            name='NPC',
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
        migrations.AddField(
            model_name='uniqueweapon',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tierra_media.character'),
        ),
        migrations.AddField(
            model_name='uniquearmor',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tierra_media.character'),
        ),
        migrations.AddField(
            model_name='commonweapon',
            name='owner',
            field=models.ManyToManyField(to='tierra_media.character'),
        ),
        migrations.AddField(
            model_name='commonarmor',
            name='owner',
            field=models.ManyToManyField(to='tierra_media.character'),
        ),
    ]
