# Generated by Django 4.2.19 on 2025-02-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0013_commonarmor_commonweapon_uniquearmor_uniqueweapon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='npc',
            field=models.BooleanField(default=False),
        ),
    ]
