# Generated by Django 4.2.19 on 2025-02-17 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tierra_media", "0014_alter_character_npc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Armor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("defense", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Backpack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tierra_media.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("damage", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
                (
                    "backpack",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="tierra_media.backpack",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="commonweapon",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="uniquearmor",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="uniqueweapon",
            name="owner",
        ),
        migrations.DeleteModel(
            name="CommonArmor",
        ),
        migrations.DeleteModel(
            name="CommonWeapon",
        ),
        migrations.DeleteModel(
            name="UniqueArmor",
        ),
        migrations.DeleteModel(
            name="UniqueWeapon",
        ),
        migrations.AddField(
            model_name="armor",
            name="backpack",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tierra_media.backpack",
            ),
        ),
        migrations.AddField(
            model_name="armor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
