# Generated by Django 4.2.18 on 2025-02-17 10:42

from django.db import migrations


def starting_factions(apps, schema_editor):
    Faction = apps.get_model("tierra_media", "Faction")
    Faction.objects.create(name="La Comunidad del Anillo")
    Faction.objects.create(name="Lothlorien")
    Faction.objects.create(name="Rivendel")
    Faction.objects.create(name="Mordor")
    Faction.objects.create(name="Isengard")


def starting_locations(apps, schema_editor):
    Location = apps.get_model("tierra_media", "Location")
    Location.objects.create(name="Minas Tirith")
    Location.objects.create(name="Bosque Negro")
    Location.objects.create(name="Lothlorien")
    Location.objects.create(name="Hobbiton")
    Location.objects.create(name="Rivendel")
    Location.objects.create(name="Isengard")
    Location.objects.create(name="Mordor")


def starting_races(apps, schema_editor):
    Race = apps.get_model("tierra_media", "Race")
    Race.objects.create(name="Humano")
    Race.objects.create(name="Elfo")
    Race.objects.create(name="Enano")
    Race.objects.create(name="Hobbit")
    Race.objects.create(name="Orco")


class Migration(migrations.Migration):

    dependencies = [
        ("tierra_media", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(starting_factions),
        migrations.RunPython(starting_locations),
        migrations.RunPython(starting_races),
    ]
