# Generated by Django 4.2.19 on 2025-02-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0015_armor_backpack_weapon_remove_commonweapon_owner_and_more'),
        ('tierra_media', '0015_auto_20250217_1042'),
    ]

    operations = [
    ]
