# Generated by Django 4.2.18 on 2025-02-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0015_auto_20250217_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(choices=[('La Comunidad del Anillo', 'La Comunidad del Anillo'), ('Lothlorien', 'Lothlorien'), ('Rivendel', 'Rivendel'), ('Mordor', 'Mordor'), ('Isengard', 'Isengard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(choices=[('Minas Tirith', 'Minas Tirith'), ('Bosque Negro', 'Bosque Negro'), ('Lothlorien', 'Lothlorien'), ('Hobbiton', 'Hobbiton'), ('Rivendel', 'Rivendel'), ('Isengard', 'Isengard'), ('Mordor', 'Mordor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('Humano', 'Humano'), ('Elfo', 'Elfo'), ('Enano', 'Enano'), ('Hobbit', 'Hobbit'), ('Orco', 'Orco')], max_length=50),
        ),
    ]
