# Generated by Django 5.1.6 on 2025-02-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0016_alter_faction_name_alter_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
