# Generated by Django 4.2.19 on 2025-02-26 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tierra_media.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tierra_media', '0016_merge_20250226_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='armor',
            name='type',
        ),
        migrations.AddField(
            model_name='armor',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='character',
            name='equipped_armor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tierra_media.armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='equipped_weapon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tierra_media.weapon'),
        ),
        migrations.AddField(
            model_name='character',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='character',
            name='sex',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='backpack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tierra_media.backpack'),
        ),
        migrations.AlterField(
            model_name='armor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50, validators=[tierra_media.models.validate_character_name]),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(choices=[('La Comunidad del Anillo', 'La Comunidad del Anillo'), ('Lothlorien', 'Lothlorien'), ('Rivendel', 'Rivendel'), ('Mordor', 'Mordor'), ('Isengard', 'Isengard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(choices=[('Minas Tirith', 'Minas Tirith'), ('Bosque Negro', 'Bosque Negro'), ('Lothlorien', 'Lothlorien'), ('Hobbiton', 'Hobbiton'), ('Rivendel', 'Rivendel'), ('Isengard', 'Isengard'), ('Mordor', 'Mordor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('Humano', 'Humano'), ('Elfo', 'Elfo'), ('Enano', 'Enano'), ('Hobbit', 'Hobbit'), ('Orco', 'Orco')], max_length=50),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='backpack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tierra_media.backpack'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
