# Generated by Django 4.2.19 on 2025-02-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tierra_media",
            "0015_armor_backpack_weapon_remove_commonweapon_owner_and_more",
        ),
        ("tierra_media", "0016_alter_faction_name_alter_location_name_and_more"),
    ]

    operations = []
