# Generated by Django 4.2.19 on 2025-02-26 21:18

from django.db import migrations, models
import tierra_media.models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0017_remove_armor_type_armor_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50, validators=[tierra_media.models.validate_character_name]),
        ),
    ]
