# Generated by Django 4.2.19 on 2025-02-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0017_character_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonarmor',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/armor-icons/'),
        ),
        migrations.AddField(
            model_name='commonweapon',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/weapon-icons/'),
        ),
        migrations.AddField(
            model_name='uniquearmor',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/armor-icons/'),
        ),
        migrations.AddField(
            model_name='uniqueweapon',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/weapon-icons/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='icon',
            field=models.ImageField(blank=True, default='', upload_to='uploads/character-icons/'),
            preserve_default=False,
        ),
    ]
