# Generated by Django 4.2.19 on 2025-02-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tierra_media", "0017_character_icon"),
        ("tierra_media", "0017_merge_20250217_1242"),
    ]

    operations = []
