# Generated by Django 4.2.19 on 2025-02-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0017_merge_20250217_1242'),
        ('tierra_media', '0018_commonarmor_icon_commonweapon_icon_uniquearmor_icon_and_more'),
    ]

    operations = [
    ]
