# Generated by Django 4.2.19 on 2025-02-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tierra_media", "0018_merge_0017_character_icon_0017_merge_20250217_1242"),
    ]

    operations = [
        migrations.AddField(
            model_name="armor",
            name="icon",
            field=models.ImageField(blank=True, upload_to="uploads/armor-icons/"),
        ),
        migrations.AddField(
            model_name="weapon",
            name="icon",
            field=models.ImageField(blank=True, upload_to="uploads/weapon-icons/"),
        ),
        migrations.AlterField(
            model_name="character",
            name="icon",
            field=models.ImageField(
                blank=True, default="", upload_to="uploads/character-icons/"
            ),
            preserve_default=False,
        ),
    ]
