# Generated by Django 4.2.18 on 2025-02-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0019_merge_20250218_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/armor-icons/'),
        ),
        migrations.AddField(
            model_name='character',
            name='sex',
            field=models.CharField(blank=True, max_length=1, unique=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/weapon-icons/'),
        ),
    ]
