# Generated by Django 4.2.19 on 2025-02-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0019_merge_20250224_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/armor-icons/'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/weapon-icons/'),
        ),
    ]
