# Generated by Django 4.2.18 on 2025-02-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0020_armor_icon_character_sex_weapon_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='sex',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1),
        ),
    ]
