# Generated by Django 4.2.19 on 2025-02-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0020_armor_icon_weapon_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='equipped_armor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tierra_media.armor'),
        ),
        migrations.AddField(
            model_name='character',
            name='equipped_weapon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tierra_media.weapon'),
        ),
    ]
