# Generated by Django 4.2.19 on 2025-02-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0021_character_equipped_armor_character_equipped_weapon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='type',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
