# Generated by Django 4.2.19 on 2025-02-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0021_alter_character_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
