# Generated by Django 4.2.19 on 2025-02-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0019_merge_20250224_1659'),
        ('tierra_media', '0022_alter_character_icon'),
    ]

    operations = [
    ]
