# Generated by Django 4.2.18 on 2025-02-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0019_armor_icon_weapon_icon_alter_character_icon'),
        ('tierra_media', '0022_remove_armor_type_delete_relationship'),
        ('tierra_media', '0023_merge_20250224_1753'),
    ]

    operations = [
    ]
