# Generated by Django 4.2.18 on 2025-02-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0024_merge_20250225_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
