# Generated by Django 4.2.18 on 2025-02-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tierra_media', '0026_alter_armor_backpack_alter_armor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
